### ISSUE TITLE
Manuelle Installation ohne Composer

### ISSUE THREAD

**Issue by wompip** [cboelter/contao-leads-optin#1]
Hi, die Erweiterung macht mich sehr neugierig, denn es ist anscheinend genau das, was ich benötige! Leider habe ich ein Problem mit der Installation auf Contao 3.5.27, weil mir Composer nicht zur Verfügung steht. Ich habe es auf die alte Art versucht (alles in einen Ordner "leads-optin" im modules-Ordner, aber das ging leider schief. Eine kleine Anleitung, was wohin muss, wäre also großartig.

Benötige ich die Erweiterungen
- composer-plugin
- meta-palettes
auch dann, wenn ich den Composer umgehen kann?

**Comment by cboelter** [comment]
Hi,
die alte Art funktioniert leider mit dem Modul aktuell nicht. Da Composer zwingend als ClassLoader verwendet wird. Man könnte es aber durchaus auf den NamespaceClassLoader von Terminal42 umbauen, der ist per altem Extension-Repository verfügbar. MetaPalettes könnte man ebenfalls durch die normale Palette config ersetzen. Insgesamt denke ich ein Aufwand von 1,0 Stunde.

Bei Interesse gerne eine Mail schicken für weitere Details.

**Comment by wompip** [comment]
Hm, ok. Vor die Composer-Wand werde ich ja tendenziell in Zukunft öfter rennen. Daher versuche ich den jetzt erstmal zum Laufen zu bringen. Falls ich damit scheitere, melde ich mich gern nochmal ;-)
