### ISSUE TITLE
Export csv contains field value + name

### ISSUE THREAD

**Issue by Kahmoon** [cboelter/contao-leads-optin#12]
The "OptIn CSV Export" output has field value **and** field name. 

"Telefonnummer [**0173123456**]","Straße/Hausnummer [**Elsenheimerstr 5224**]"

Is it possible to get just values (bold) on export? Otherwise its quite complicated to handle data afterwards. This export type has no options at all (https://github.com/cboelter/contao-leads-optin/issues/5). 

<img width="979" alt="Bildschirmfoto 2022-03-02 um 13 26 11" src="https://user-images.githubusercontent.com/6390770/156361406-e21ea501-67fa-477a-bc2f-00d4b68e9625.png">

**Comment by Kahmoon** [comment]
May i bump this? This is still an issue :-D

**Comment by zoglo** [comment]
@Kahmoon

This feature has to be added within https://github.com/terminal42/contao-leads.
You should open an issue in the mentioned bundle
