### ISSUE TITLE
After including the module "OptIn processing" in an article, it can no longer be edited

### ISSUE THREAD

**Issue by GregorBaiker** [cboelter/contao-leads-optin#17]
First, thanks for programming the contao-leads-optin plugin. After including the module "OptIn processing" in an article, it can no longer be edited. See the following shreenshot. I use the new plugin version 1.3 with Contao version 4.13.14.

Greetings,
Gregor Baiker

![leads-optin-error](https://user-images.githubusercontent.com/84313069/210445367-ea32a462-646f-4794-82d4-38f77481a059.jpg)

**Comment by GregorBaiker** [comment]
PHP Version 7.4.33

**Comment by cboelter** [comment]
@GregorBaiker this should be fixed with new 2.0.0 release. Could you please check this?

**Comment by GregorBaiker** [comment]
Hello,


It is not posible to get detailed plugin informations in the contao manager.

 

 
Also no new version is shown in the contao manager.


 
What can I do?





 
Von: Christopher Bölter ***@***.***>
Gesendet: Donnerstag, 5. Januar 2023 17:24
An: cboelter/contao-leads-optin ***@***.***>
Cc: GregorBaiker ***@***.***>; Mention ***@***.***>
Betreff: Re: [cboelter/contao-leads-optin] After including the module "OptIn processing" in an article, it can no longer be edited (Issue #17)

 
@GregorBaiker this should be fixed with new 2.0.0 release. Could you please check this?

**Comment by cboelter** [comment]
Try the update button, then apply changes and try to update it. I'm not sure how the manager gets the latest version of a package but if you start the update the current version is loaded.

**Comment by GregorBaiker** [comment]
Hello Christopher,

 
the plugin update works only if I set the version manual to 2.0. Now I can show the Details. But the Plugin is markt as unknown version. Something gos wrong with the Contao Manager.

 

 
The bug with the artikel including the Opt-In module is no fixt. Thanks a lot.

 
Best regards,

Gregor

 
Von: Christopher Bölter ***@***.***>
Gesendet: Freitag, 6. Januar 2023 12:53
An: cboelter/contao-leads-optin ***@***.***>
Cc: GregorBaiker ***@***.***>; Mention ***@***.***>
Betreff: Re: [cboelter/contao-leads-optin] After including the module "OptIn processing" in an article, it can no longer be edited (Issue #17)

 
Try the update button, then apply changes and try to update it. I'm not sure how the manager gets the latest version of a package but if you start the update the current version is loaded.

**Comment by GregorBaiker** [comment]
I forgot to close...
This issue is fixed and work well.
Thanks
