### ISSUE TITLE
leadOptInErrorMessage does not have a default value

### ISSUE THREAD

**Issue by kaeptn2lvl** [cboelter/contao-leads-optin#6]
just installed your extension. thx for sharing :D 
es scheint da ein problem bzgl. dem FE Modul zu geben. Bei Klick auf "Neues Modul" kommt eine Fehlermeldung:

> An exception occurred while executing 'INSERT INTO tl_module (`type`, `cols`, `queryType`, `contextLength`, `totalLength`, `perPage`, `searchType`, `inColumn`, `source`, `rss_cache`, `rss_template`, `numberOfItems`, `list_layout`, `list_info_layout`, `news_featured`, `news_metaFields`, `news_template`, `news_format`, `news_startDay`, `news_order`, `nl_template`, `cal_startDay`, `cal_format`, `cal_order`, `cal_template`, `cal_ctemplate`, `com_order`, `com_template`, `tag_tagtable`, `tag_tagfield`, `tag_maxtags`, `tag_buckets`, `tag_topten_number`, `articlelist_template`, `cloud_template`, `scope_template`, `clear_text`, `articlelist_tpl`, `articlelist_firstorder`, `articlelist_secondorder`, `pid`, `tstamp`) VALUES ('navigation', '2cl', 'and', 48, 1000, 0, 'simple', 'main', 'internal', 3600, 'rss_default', 3, 'list_default', 'info_default', 'all_items', 'a:2:{i:0;s:4:\"date\";i:1;s:6:\"author\";}', 'news_latest', 'news_month', 0, 'descending', 'nl_simple', 1, 'cal_month', 'ascending', 'event_full', 'cal_default', 'ascending', 'com_default', 'tl_tag', 'tag', '0', '4', '10', 'mod_global_articlelist', 'mod_tagcloud', 'mod_tagscope', 'Auszeichnungen', 'mod_global_articlelist', 'title ASC', '', '2', 0)': SQLSTATE[HY000]: **General error: 1364 Field 'leadOptInErrorMessage' doesn't have a default value**

Workaround: Ein bestehendes Modul duplizieren und dann ändern
oder
in tl_modul an entpsrechneder stelle einen default wert 'NULL' eintragen

**Comment by fritzmg** [comment]
See #9

**Comment by cboelter** [comment]
Thanks to @fritzmg ! I have created a new bugfix release.
