### ISSUE TITLE
Virenscanner betätigen OptIn Link

### ISSUE THREAD

**Issue by dive13** [cboelter/contao-leads-optin#8]
Ich habe zunehmend das Problem, dass Antiviren-Software auf Empfängerseite die Mails scannt und die OptIn URL bereits VOR dem eigentlichen User aufruft. Damit ist die Bestätigung bereits gesetzt, ohne dass der User das ggf. so will, bzw. bekommt dieser nur mehr den Text der OptIn-Fehlermeldung zu sehen und ist verwirrt.

Gibt es eine Möglichkeit, dass der Link nicht gleich das OptIn ausführt, sondern zu einer Bestätigungsseite führt, wo der User das OptIn per Button bestätigen muss?

**Comment by cboelter** [comment]
@dive13 ja das wäre möglich. Dafür müsste man das Modul allerdings anpassen. Besteht die Möglichkeit die Entwicklung zu sponsorn?

**Comment by cboelter** [comment]
Fixed with https://github.com/cboelter/contao-leads-optin/releases/tag/1.2.0
